proxyServers: http://localhost:8801,http://localhost:8802,http://localhost:8803
proxyPort: 8888
# inbound 线程池
inbound:
  corePoolSize: 4
  maxPoolSize: 8
  queueCapacity: 100
  keepAliveSeconds: 60
# outbound 线程池
outbound:
  corePoolSize: 4
  maxPoolSize: 8
  queueCapacity: 100
  keepAliveSeconds: 60
