server:
  port: 8091

spring:
  application:
    name: demo-consumer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3316/hmily_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
hmily:
  support:
    rpc:
      annotation: true

logging:
  level:
    root: error
    org.springframework.web: info
    org.apache.ibatis: debug
    org.dromara.hmily.demo.bonuspoint: debug
    org.dromara.hmily.demo.lottery: debug
    org.dromara.hmily.demo: debug
    io.netty: info
  file:
    path: "./logs"